x-default-logging: &default-logging
  driver: local
  options:
    max-size: "${DOCKER_LOG_MAX_SIZE:-10m}"
    max-file: "${DOCKER_LOG_MAX_FILES:-5}"

services:
  redis:
    image: redis:alpine
    container_name: redis
    logging: *default-logging
    environment:
      REDIS_CONFIG: |
        unixsocket /var/run/redis/redis.sock
        unixsocketperm 777
    command:
      sh -c "echo \"$$REDIS_CONFIG\" > /etc/redis.conf && redis-server /etc/redis.conf"
    volumes:
      - redis-data:/data
      - redis-socket:/var/run/redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/var/run/redis/redis.sock", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s

  tunnelquestbot:
    image: ghcr.io/jamesjamail/tunnelquestbot/prod/tunnelquestbot:latest
    container_name: tunnelquestbot
    logging: *default-logging
    depends_on:
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "${SQLITE_DATABASE_URL:-file:/data/tunnelquestbot.db}"
      POSTGRES_MIGRATION_URL: "${POSTGRES_MIGRATION_URL:-}"
      SERVERS_BLUE_LOG_FILE_PATH: "/logfiles/${SERVERS_BLUE_LOG_FILE}"
      SERVERS_GREEN_LOG_FILE_PATH: "/logfiles/${SERVERS_GREEN_LOG_FILE}"
      SERVERS_RED_LOG_FILE_PATH: "/logfiles/${SERVERS_RED_LOG_FILE}"
      REDIS_SOCKET_DIR: "${REDIS_SOCKET_DIR}"
      FAKE_LOGS: "${FAKE_LOGS:-false}"
      DEBUG_MODE: "${DEBUG_MODE:-false}"
    volumes:
      - type: bind
        source: "${LOG_SOURCE_PATH}"
        target: /logfiles
      - type: bind
        source: ".env"
        target: /app/.env
      - sqlite-data:/data
      - "redis-socket:${REDIS_SOCKET_DIR}"
    restart: always

volumes:
  sqlite-data:
  redis-socket:
  redis-data:
